language: java

notifications:
  slack: luceeserver:ZTfbu4bVSLFmakRcLInrNZIT
  email:
    - michael@lucee.org

#after_success:
#  - git commit -a -m "Committed by Travis-CI build number: $TRAVIS_JOB_ID"



