language: java

# copy the settings.xml for maven from the "travis" branch
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -f loader/pom.xml clean deploy --settings target/travis/settings.xml || mvn -f loader/pom.xml clean install"

# whitelist
branches:
  only:
    - master
 

notifications:
  slack: luceeserver:ZTfbu4bVSLFmakRcLInrNZIT
  email:
    - info@lucee.org
    - michael@lucee.org

# oldscript: mvn -f loader/pom.xml clean deploy